version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: booking_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: booking_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
    ports:
      - "5432:5432"
   
    networks:
      - red_booking_interna

  api:
    build: ./server
    container_name: booking_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password123@db:5432/booking_system
    volumes:
      - ./server:/app
    networks:
      - red_booking_interna

volumes:
  postgres_data:

networks:
  red_booking_interna:
    name: booking_network
    driver: bridge